name: Automate
on:
  schedule:
    - cron: "*/5 * * * *"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v4

      - name: Setup Python Version
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Execute a python script
        working-directory: .github/scripts
        env:
          APPLICATION_SECRET: ${{ secrets.APPLICATION_SECRET }}
          APPLICATION_ID: ${{ secrets.APPLICATION_ID }}
          SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
        run: python automate.py --azure_application_secret $APPLICATION_SECRET --azure_application_id $APPLICATION_ID --azure_subscription_id $SUBSCRIPTION_ID