name: Automate
on:
  schedule:
    - cron: "*/1 * * * *"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v4

      - name: Setup Python Version
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: 'pip'

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Execute Python script
        run: /usr/ automate.py